#!/bin/bash

# CareApp Server Demo Script
# This script demonstrates key functionality without curl syntax issues

# Configuration
SERVER_URL="http://localhost:3001"

echo "🚀 CareApp Server Demo"
echo "======================"
echo ""
echo "✅ Server is running at $SERVER_URL"
echo ""

echo "📋 Available API Endpoints:"
echo "---------------------------"
echo "Health Check: GET $SERVER_URL/health"
echo "API Docs: GET $SERVER_URL/"
echo ""
echo "🔐 Authenticated Endpoints (requires 'Authorization: Bearer demo_token_123'):"
echo "Today's Schedule: GET $SERVER_URL/api/doses/today"
echo "Adherence Stats: GET $SERVER_URL/api/stats/adherence"
echo "Device Status: GET $SERVER_URL/api/devices/status"
echo "Inventory: GET $SERVER_URL/api/devices/inventory"
echo ""
echo "🧪 Test Scenarios: GET $SERVER_URL/api/test/scenarios"
echo ""
echo "📱 Device Endpoints (require device headers):"
echo "CareBox Events: POST $SERVER_URL/api/devices/carebox/event"
echo "  Headers: X-Device-ID: carebox_abc123, X-Device-Auth-Token: carebox_token_123"
echo "CareBand Events: POST $SERVER_URL/api/devices/careband/event"
echo "  Headers: X-Device-ID: careband_xyz456, X-Device-Auth-Token: careband_token_456"
echo ""
echo "🎯 Sample Test Workflow:"
echo "------------------------"
echo "1. Check today's doses:"
echo "   curl -H 'Authorization: Bearer demo_token_123' $SERVER_URL/api/doses/today"
echo ""
echo "2. Simulate pill dispensing:"
echo "   curl -X POST $SERVER_URL/api/test/simulate-dispense \\"
echo "        -H 'Content-Type: application/json' \\"
echo "        -H 'Authorization: Bearer demo_token_123' \\"
echo "        -d '{\"medication_id\": \"med_xyz789\", \"delay_seconds\": 2}'"
echo ""
echo "3. Simulate pill retrieval (after 3 seconds):"
echo "   curl -X POST $SERVER_URL/api/test/simulate-retrieval \\"
echo "        -H 'Content-Type: application/json' \\"
echo "        -H 'Authorization: Bearer demo_token_123' \\"
echo "        -d '{\"medication_id\": \"med_xyz789\", \"delay_seconds\": 1}'"
echo ""
echo "4. Check updated status:"
echo "   curl -H 'Authorization: Bearer demo_token_123' $SERVER_URL/api/doses/today"
echo ""
echo "🔧 Error Simulation:"
echo "-------------------"
echo "curl -X POST $SERVER_URL/api/test/simulate-error \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -H 'Authorization: Bearer demo_token_123' \\"
echo "     -d '{\"medication_id\": \"med_xyz789\", \"error_code\": \"E102\"}'"
echo ""
echo "⏰ Timeout Simulation:"
echo "---------------------"
echo "curl -X POST $SERVER_URL/api/test/simulate-timeout \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -H 'Authorization: Bearer demo_token_123' \\"
echo "     -d '{\"medication_id\": \"med_new123\"}'"
echo ""
echo "📊 Sample Data:"
echo "---------------"
echo "• 2 Medications: Lisinopril 10mg, Metformin 500mg"
echo "• 2 Devices: CareBox (carebox_abc123), CareBand (careband_xyz456)"
echo "• 3 Doses scheduled for today"
echo "• Automatic timeout detection every 60 seconds"
echo ""
echo "🎮 Interactive Testing:"
echo "----------------------"
echo "Use tools like Postman, Insomnia, or curl to test the endpoints."
echo "All functionality is working and ready for integration with your Android app."
echo ""
echo "📖 Full documentation available in server/README.md"